2023-09-07 16:43:20,818 | ERROR | Internal Server Error: /news/ | C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\log.py | (<class 'django.template.exceptions.TemplateDoesNotExist'>, TemplateDoesNotExist('new.html, news/post_list.html'), <traceback object at 0x000002303A30C4C0>)
Traceback (most recent call last):
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: new.html, news/post_list.html
2023-09-07 16:43:22,305 | ERROR | "GET /news/ HTTP/1.1" 500 145 | C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\servers\basehttp.py | None
